### ISSUE TITLE
After latest Broad Single Cell portal update, tSNE plot failing to show

### ISSUE THREAD

**Issue by jncampbe** [broadinstitute/single_cell_portal#20] opened 2018-02-01 13:42 UTC
Hello,
As of today, I'm no longer able to load a tSNE for the following study on the Broad Single Cell Portal:

      Study: A molecular census of arcuate hypothalamus and median eminence cell types 20921 cells
      Cluster: Neurons Only 2d
      Annotation: Neurons Only Clusters

Please advise... 
Thank you!
John

**Comment by bistline** [comment] 2018-02-01 14:43
We are not able to reproduce the error - the plot you indicated is loading fine for us.  Can you clear your browser cache and try again?

**Comment by jncampbe** [comment] 2018-02-01 14:48
I cleared my Chrome browser, closed and reopened it but the error still occurred. Also, I switched to my Safari browser but got the same error. Here’s what it looks like…

**Comment by bistline** [comment] 2018-02-01 14:57
The screenshot didn't attach - can you try again?  Also, I looked at the production logs and there are no errors from the server.  However, what I did just see when trying in Safari is that the legend was covering up the plot area so that the clusters were not viewable when viewing with the browser on a smaller viewport.  Is this what you're seeing?

**Comment by jncampbe** [comment] 2018-02-01 15:06
Here’s the file attachment again. I’ve tried using the auto-scale, pan, and reset scale features but none of them make the tSNE visible. However, if I minimize the window, I can see the edge of the tSNE from behind the key, so I think that you’re right about the key covering the tSNE. I can’t figure out how to fix it though.

**Comment by bistline** [comment] 2018-02-01 15:15
The screenshot still didn't attach, but I think what I saw is what you are seeing.  This is definitely a new bug, so we'll open an issue on our end and try to get a fix in for the next release.  In the meantime, I would try maximizing the browser window and closing both options panels on the left & right and using the 'reset axes' button in the plot.

**Comment by jncampbe** [comment] 2018-02-01 15:17
Thanks for looking into it. I converted the screenshot to a PDF and re-attached.

**Comment by eweitz** [comment] 2018-02-01 15:20
@jncampbe, could you try attaching the screenshot using the GitHub web UI?  A PNG or JPG should work fine there.

**Comment by jncampbe** [comment] 2018-02-01 15:22
<img width="1274" alt="screen shot 2018-02-01 at 9 48 12 am" src="https://user-images.githubusercontent.com/36040379/35686221-c9433002-0739-11e8-881a-3ab6ef0514ac.png">

**Comment by eweitz** [comment] 2018-02-01 15:23
Thank you!  That confirms our suspicion on the nature of this bug.  We'll update here when this is fixed.

**Comment by jncampbe** [comment] 2018-02-01 15:24
Thanks Eric! I’ll stay tuned…

**Closed** 2018-05-01 15:50 UTC
