### ISSUE TITLE
uploading gene list results in inexact matches

### ISSUE THREAD

**Issue by pzumbo** [broadinstitute/single_cell_portal#11] opened 2017-04-24 19:24 UTC
Not sure if this is intended, but if I upload a gene list, for example, 

POU5F1
SOX2
NANOG
PRDM14,

the following genes are returned in the expression heatmap:

POU5F1 POU5F1B POU5F1P3 POU5F1P4 QSOX2 SOX2 SOX21 NANOG NANOGP1 NANOGP8 PRDM14

I would have expected exact matches only, or at least an option.

**Comment by bistline** [comment] 2017-04-24 19:29
If there are exact matches, then yes - it should default to those.  It should only fall back to partial matches if there isn't an exact one available.  I'll take a look at it.

**Comment by friedue** [comment] 2017-04-24 19:51
our collaborator gave us a gene list to make a heatmap of expression values - the list kept on crashing the portal for me although it only contained 4 genes. but one of the gene names was just "T", so my guess is that it was trying to return all genes starting with a T...? No idea how to safeguard against this, just wanted to chime in.

**Comment by bistline** [comment] 2017-04-24 20:09
Thanks for the heads-up.  That is possible, although since T is a valid gene name, if the study has expression values for T then they should back in the query.  Could you send me a copy of the gene list, along with the name of the study you were querying?

I've confirmed that the production portal is not behaving correctly for exact matches.  This has already been addressed as part our next update, but that's not due to be deployed for a bit, so I'll go ahead and deploy a fix for this specifically soon.

**Comment by friedue** [comment] 2017-04-24 20:54
You're right, T as a gene name was not part of the list that we uploaded (because we filtered the genes). Still, that's not the most optimal behavior although I don't really know how to hit the sweet spot between user-friendly auto-complete and portal-friendly exact matches only behavior.

**Comment by bistline** [comment] 2017-04-24 20:59
The UI based auto-complete ignores everything below two characters, but if you upload a gene list it bypasses that.  I've come up with a decent workaround for this of only allowing exact matches for genes below 2 characters, and partial matches above that.  My local testing worked correctly, so I just deployed the fix - please let me know if you are still seeing any behavior like this.

**Comment by friedue** [comment] 2017-04-26 18:30
looks good for now!

**Closed** 2017-04-26 19:48 UTC
