### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by sjwalker223** [broadinstitute/single_cell_portal#74] opened 2019-09-08 23:46 UTC
After logging in to my account (but not before), I keep getting a page showing 'We're sorry, but something went wrong. Please report an issue if this problem persists.'
The 'My Studies' tab is blanked out, and I can't access any page on the portal at all.

**Comment by bistline** [comment] 2019-09-09 14:04
sjwalker223 -

Thanks for letting us know - I'm looking into the issue right now.  I'll let you know what I find.

Best,

Jon
Single Cell Portal Team

**Comment by bistline** [comment] 2019-09-09 15:28
I have a question: did you recently update anything about your FireCloud/Terra registration?  I am seeing a discrepancy between what our database says about your FireCloud registration and what their API says - we show you as registered, but their API returns a 401 (which means they think you are not).  I'm wondering if you changed the email associated with that account recently.

**Comment by sjwalker223** [comment] 2019-09-09 15:36
Thanks for the update. I didn't change the email, but something weird did happen with Google account associated with this institutional email address - I had to make a new associated Google account when I tried to log in to the single cell portal. I'm not sure if this was because the Google account was temporary, or because of the Firecloud->Terra transition, but I think the latter. I tried to login on Terra, but when I do so it takes me to the new user registration page; then when I try to register as a new user it comes up with an error.

**Comment by sjwalker223** [comment] 2019-09-09 15:36
Sorry, closed by accident

**Comment by bistline** [comment] 2019-09-09 15:41
OK - that would definitely account for it then.  So I can do the following in the meantime to unblock you on the Single Cell Portal: I'll mark your user account as not being registered for Terra, and that will allow you to sign in and see your studies.  In the meantime, I've notified engineers on Terra of the issue, and they are looking into your account to see what the problem is.

Any studies that were shared with you via a Terra user group will not show up until we can solve this issue (this is actually where the error was being thrown).  If at the end of the day you need to use a different email address in Terra & Single Cell Portal, then I can migrate any shared studies with you to a new Google account so that you don't lose access to any studies.

I'll leave this issue open in the meantime while they debug things on the Terra side.

Best,

Jon

**Comment by sjwalker223** [comment] 2019-09-09 15:53
OK, that's great, thanks! Account is working, and I can still see the studies that were shared with me (so presumably they were not shared via a Terra user group). So I guess there is no issue if the email address for Terra ends up being different.

Thanks very much,
Sam

**Comment by jlchang** [comment] 2019-09-18 14:25
Hi @sjwalker223,

Glad to hear your account is working. There is an underlying issue that could become problematic in future. To investigate further, we'd want to confirm your institutional email address but don't want that information captured in this github issue. If you could e-mail our support address, scp-support@broadinstitute.zendesk.com, we can follow-up on those details and then coordinate with the Terra team to resolve the underlying issue.

Regards,

Jean

PS. I'll close this issue in anticipation of following up via Zendesk.

**Closed by jlchang** 2019-09-18 14:25 UTC
